# Generated by Django 6.0.1 on 2026-01-28 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название звена сети", max_length=350, verbose_name="Название звена сети"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Укажите задолженность перед поставщиком",
                        max_digits=12,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Укажите время создания", verbose_name="Время создания"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="networks.network",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(help_text="Введите почту", max_length=150, verbose_name="Почта")),
                ("country", models.CharField(help_text="Введите страну", max_length=100, verbose_name="Страна")),
                ("city", models.CharField(help_text="Введите город", max_length=100, verbose_name="Город")),
                ("street", models.CharField(help_text="Введите улицу", max_length=100, verbose_name="Улица")),
                (
                    "house_number",
                    models.CharField(help_text="Введите номер дома", max_length=20, verbose_name="Номер дома"),
                ),
                (
                    "network",
                    models.OneToOneField(
                        help_text="Введите звено сети",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="networks.network",
                        verbose_name="Звено сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактные данные",
                "verbose_name_plural": "Контактные данные",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название продукта", max_length=350, verbose_name="Название продукта"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Введите модель продукта", max_length=350, verbose_name="Название модели продукта"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        help_text="Укажите дату выхода продукта на рынок", verbose_name="Дата выхода продукта на рынок"
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        help_text="Введите звено сети",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="networks.network",
                        verbose_name="Звено сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
