# Generated by Django 6.0.1 on 2026-01-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name="Уровень поставщика в иерархии"),
        ),
    ]
