# Generated by Django 6.0.1 on 2026-01-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0002_network_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Время создания"),
        ),
        migrations.AlterField(
            model_name="network",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Укажите задолженность перед поставщиком",
                max_digits=12,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
    ]
